version: '3.2'

services:

  db:
    image: "mdillon/postgis:9.6"
    environment:
      POSTGRES_USER: pycsw
      POSTGRES_PASSWORD: pycsw
      POSTGRES_DB: pycsw
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "db-data:/var/lib/postgresql/data/pgdata"

  web:
    build:
      context: "."
    volumes:
      - "./test/force:/force"
      - "./test/export:/export"
      - "./test/store:/store"
      - "./testing.cfg:/opt/pycsw/default.cfg:ro"
    ports:
      - "8000:8000"

volumes:
  db-data:
